In [1]:
import pandas as pd 

df1 = pd.read_csv(r"E:\File Program\Semester II\Jupyter Notebook\Data Latihan\data\New folder (3)\decisiontree_ch6.csv")
df1

    ID   mesin  bangku penggerak    label
0    1  bensin       4     depan    sedan
1    2  bensin       2     depan    sedan
2    3  bensin       8  belakang  minibus
3    4  diesel       6     depan  minibus
4    5  bensin       5  belakang  minibus
5    6  diesel       8  belakang  minibus
6    7  diesel       8  belakang  minibus
7    8  bensin       4     depan    sedan
8    9  diesel       7  belakang  minibus
9   10  bensin       4     depan    sedan
10  11  bensin       2     depan    sedan
11  12  diesel       6  belakang  minibus
12  13  diesel       8     depan  minibus
13  14  bensin       4     depan    sedan
14  15  diesel       2     depan    sedan
15  16  bensin       4     depan    sedan
16  17  bensin       8  belakang  minibus
17  18  bensin       4     depan    sedan
18  19  diesel       8  belakang  minibus
19  20  diesel       8  belakang  minibus
20  21  bensin       4     depan    sedan
21  22  bensin       4     depan  minibus
22  23  diesel       8  belakang  minibus
23  24  bensin       4     depan    sedan
24  25  bensin       5  belakang  minibus
25  26  bensin       4     depan  minibus
26  27  diesel       8  belakang  minibus
27  28  bensin       4     depan    sedan
28  29  bensin       7  belakang  minibus
29  30  bensin       4     depan    sedan
30  31  bensin       4     depan    sedan
31  32  bensin       2     depan    sedan
32  33  bensin       8  belakang  minibus
33  34  diesel       6     depan  minibus
34  35  bensin       5  belakang  minibus
35  36  diesel       8  belakang  minibus
36  37  diesel       4  belakang  minibus
37  38  bensin       4     depan    sedan
38  39  diesel       5  belakang  minibus
39  40  bensin       4     depan    sedan

In [2]:
encoding = {
    "mesin": {"bensin": 0, "diesel": 1},
    "penggerak": {"depan": 0, "belakang": 1}
}

df1.replace(encoding, inplace = True)
df1

    ID  mesin  bangku  penggerak    label
0    1      0       4          0    sedan
1    2      0       2          0    sedan
2    3      0       8          1  minibus
3    4      1       6          0  minibus
4    5      0       5          1  minibus
5    6      1       8          1  minibus
6    7      1       8          1  minibus
7    8      0       4          0    sedan
8    9      1       7          1  minibus
9   10      0       4          0    sedan
10  11      0       2          0    sedan
11  12      1       6          1  minibus
12  13      1       8          0  minibus
13  14      0       4          0    sedan
14  15      1       2          0    sedan
15  16      0       4          0    sedan
16  17      0       8          1  minibus
17  18      0       4          0    sedan
18  19      1       8          1  minibus
19  20      1       8          1  minibus
20  21      0       4          0    sedan
21  22      0       4          0  minibus
22  23      1       8          1  minibus
23  24      0       4          0    sedan
24  25      0       5          1  minibus
25  26      0       4          0  minibus
26  27      1       8          1  minibus
27  28      0       4          0    sedan
28  29      0       7          1  minibus
29  30      0       4          0    sedan
30  31      0       4          0    sedan
31  32      0       2          0    sedan
32  33      0       8          1  minibus
33  34      1       6          0  minibus
34  35      0       5          1  minibus
35  36      1       8          1  minibus
36  37      1       4          1  minibus
37  38      0       4          0    sedan
38  39      1       5          1  minibus
39  40      0       4          0    sedan

In [3]:
X = df1.drop(['ID', 'label'], axis=1)
y = df1['label']

In [4]:
import sklearn.model_selection as ms 

X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size = 0.2)

In [5]:
import sklearn.tree as tree

modell = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)
modell.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [6]:
y_prediksi = modell.predict(X_test)
print(y_prediksi)

['minibus' 'sedan' 'minibus' 'minibus' 'minibus' 'sedan' 'sedan' 'minibus']

In [7]:
import sklearn.metrics as met 

a = met.accuracy_score(y_test, y_prediksi)
print(str(a * 100) + '%')

87.5%

In [8]:
import pydotplus as pp

labels = ['mesin', 'bangku', 'penggerak']
dot_data = tree.export_graphviz(modell, out_file = None, feature_names = labels, filled = True, rounded = True)
graph = pp.graph_from_dot_data(dot_data)
graph.write_png('decisiontree.png')
#print(graph)

True

In [12]:
import sklearn.tree as tree
import sklearn.metrics as met 
import pandas as pd 
import sklearn.model_selection as ms 


df1 = pd.read_csv(r"E:\File Program\Semester II\Jupyter Notebook\Data Latihan\data\New folder (3)\decisiontree_ch6.csv")
encoding = {
    "mesin": {"bensin": 0, "diesel": 1},
    "penggerak": {"depan": 0, "belakang": 1}
}

df1.replace(encoding, inplace = True)

X = df1.drop(['ID', 'label'], axis=1)
y = df1['label']

X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size = 0.2)
modell = tree.DecisionTreeClassifier(criterion = 'gini', max_depth = 5)
modell.fit(X_train, y_train)
y_prediksi = modell.predict(X_test)
print(y_prediksi)

a = met.accuracy_score(y_test, y_prediksi)
print(str(a * 100) + '%')

['sedan' 'minibus' 'minibus' 'sedan' 'sedan' 'minibus' 'sedan' 'minibus']
75.0%

In [16]:
import pydotplus as pp

labels = ['mesin', 'bangku', 'penggerak']
dot_data = tree.export_graphviz(modell, out_file = None, feature_names = labels, filled = True, rounded = True)
graph = pp.graph_from_dot_data(dot_data)
graph.write_png('decisiontree.png')
#print(graph)

True